Installation: install wlroots headers with Meson
Hyprland plugin API requires wlroots headers. Dropping
--skip-subprojects will fix plugins but may break system wlroots.
Instead copy and adjust a part of `make installheaders`.

Example error this tries to fix:

In file included from hy3/src/main.cpp:4:
In file included from /usr/local/include/hyprland/src/Compositor.hpp:7:
In file included from /usr/local/include/hyprland/src/defines.hpp:1:
/usr/local/include/hyprland/src/includes.hpp:36:10: fatal error: 'wlr/backend.h' file not found
   36 | #include <wlr/backend.h>
      |          ^~~~~~~~~~~~~~~