issue-guidelines: fix syntax causing hugo serve error (#1201)
Fixes the following error that is emitted when running `hugo serve`:

Error: error building site: process: readAndProcessContent:
".../hyprland-wiki/content/Contributing and
Debugging/Issue-Guidelines.md:42:1": got positional parameter 'To'.
Cannot mix named and positional parameters